#!/bin/bash

##########################################################
#                                                        #
#                       GNU ecount                       #
#                                                        #
#           author: dex <dex@belle2.ifj.edu.pl>          #
#                                                        #
##########################################################

ver=1.2
num=5

title="event counter $ver"
pname="ecount"


#--- DIRs
scripthome='/bwf/g73home/stypula/script'
place=`dirname $0`

. ${scripthome}/updates

if [ $# -eq 0 ]; then
cat << EOF
_______________________________________________________________
 $title 

 usage: ecount [-MC] logfile1 logfile2 ...

 examples:  ecount mix*.log
            ecount -MC b0_fkst*.log

 use -MC option to count output events from user MC production

EOF
exit
fi

echo "------------------------------------------------------------------------------------------"
echo ""
echo "                 *** Summary of Gsim MC production ***"
echo ""
echo "           FILE (job)           | No. of INPUT events   | No. of OUTPUT events  |  Ratio"
echo "------------------------------------------------------------------------------------------"

event=0
eventIN=0
if [ $1 == "-MC" ]; then
	shift
	while [ $# -gt 0 ]
	do
                exp=$(echo $1 | awk -F '_' '{print $3}')
		ile=$(grep -c "#output events" $1)
		if [ $ile -eq 0 ]; then
			echo
			echo WARNING: NO output events number found in $1!
		else
			abc=$(grep --binary-files=text "#output events" $1 | sed -e 's/.*:.//; s/(.*//')
                        abc2=$(grep --binary-files=text "#input events" $1 | sed -e 's/.*:.//; s/(.*//')
  			xyz=$(echo $abc)
                        xyzIN=$(echo $abc2)
			event=$[event+xyz]
			eventIN=$[eventIN+xyzIN]
			ratio=`echo "scale=4; $xyz/$xyzIN" | bc`
			echo $1" "$xyzIN" "$xyz" "$ratio | awk '{print ""$1 "\t| " $2 "\t\t\t| " $3 "\t\t\t| " $4}'
			#echo $1"          |" $xyzIN "   |" $xyz "   | " $ratio
		fi
		shift
	done
else
	while [ $# -gt 0 ]
	do
		grep -A 15 "BASF Execution Statistics" $1 > ecount.temp
		ile=$(grep -c "BASF Execution Statistics" ecount.temp)
		if [ $ile -eq 0 ]; then
			echo
			echo WARNING: There is NO BASF Execution Statistics table in $1!
		else
			abc=$(grep "fix_mdst.*[|].*[|]" ecount.temp | awk '{print $6}' | tail -1)
			xyz=$(echo $abc)
			event=$[event+xyz]
		fi
		shift
		echo -n .
	done
	rm ecount.temp
fi
echo "------------------------------------------------------------------------------------------"
ratio=`echo "scale=4; $event/$eventIN" | bc`
echo "Sum "$eventIN" "$event" "$ratio | awk '{print ""$1 "\t\t\t\t| " $2 "\t\t\t| " $3 "\t\t\t| " $4}'
echo "------------------------------------------------------------------------------------------"
