/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

// Your description goes here... 

#include "Riostream.h" 

#include "RooDtLifetime.h"
#include "RooAbsReal.h" 
#include "RooAbsCategory.h"
#include "RooCategory.h"
#include "RooRealConstant.h"
#include <math.h> 
#include "TMath.h"
#include "RooCustomizer.h"

#include "tatami/tatami.h"

ClassImp(RooDtLifetime)


RooDtLifetime::RooDtLifetime(const char *name, const char *title,
		RooAbsReal& _dt,
		RooAbsReal& _tau_b0,
		RooAbsCategory& _expno,
		RooAbsReal& _costh,
		RooAbsReal& _ecms,
		RooAbsReal& _rec_vtntrk,
		RooAbsReal& _rec_vterr,
		RooAbsReal& _rec_vtchi2,
		RooAbsReal& _rec_vtndf,
		RooAbsReal& _asc_vtntrk,
		RooAbsReal& _asc_vterr,
		RooAbsReal& _asc_vtchi2,
		RooAbsReal& _asc_vtndf,
		RooAbsReal& _keeptagl,
		RooAbsCategory& _flavor,
		RooAbsReal& _wtag,
		RooAbsReal& _delta_wtag,
		double _delta_m,
		bool _mc,
		bool _addoutlier,
		double _alpha) :
		RooAbsPdf(name, title),
		dt("dt", "dt", this, _dt),
		tau_b0("tau_b0", "tau_b0", this, _tau_b0),
		expno("expno", "expno", this, _expno),
		costh("costh", "costh", this, _costh),
		ecms("ecms", "ecms", this, _ecms),
		rec_vtntrk("rec_vtntrk", "rec_vtntrk", this, _rec_vtntrk),
		rec_vterr("rec_vterr", "rec_vterr", this, _rec_vterr),
		rec_vtchi2("rec_vtchi2", "rec_vtchi2", this, _rec_vtchi2),
		rec_vtndf("rec_vtndf", "rec_vtndf", this, _rec_vtndf),
		asc_vtntrk("asc_vtntrk", "asc_vtntrk", this, _asc_vtntrk),
		asc_vterr("asc_vterr", "asc_vterr", this, _asc_vterr),
		asc_vtchi2("asc_vtchi2", "asc_vtchi2", this, _asc_vtchi2),
		asc_vtndf("asc_vtndf", "asc_vtndf", this, _asc_vtndf),
		keeptagl("keeptagl", "keeptagl", this, _keeptagl),
		flavor_cat("flavor_cat", "flavor", this, _flavor),
		wtag("wtag", "wtag", this, _wtag),
		delta_wtag("delta_wtag", "delta_wtag", this, _delta_wtag),
		delta_m(_delta_m),
		mc(_mc),
		dt_ll(Belle::dt_resol_global::dt_llmt),
		dt_ul(Belle::dt_resol_global::dt_ulmt),
		addoutlier(_addoutlier),
		alpha(_alpha) {
}

RooDtLifetime::RooDtLifetime(const char *name, const char *title,
		RooAbsReal& _dt,
		RooAbsReal& _tau_b0,
		RooAbsCategory& _expno,
		RooAbsReal& _costh,
		RooAbsReal& _ecms,
		RooAbsReal& _rec_vtntrk,
		RooAbsReal& _rec_vterr,
		RooAbsReal& _rec_vtchi2,
		RooAbsReal& _rec_vtndf,
		RooAbsReal& _asc_vtntrk,
		RooAbsReal& _asc_vterr,
		RooAbsReal& _asc_vtchi2,
		RooAbsReal& _asc_vtndf,
		RooAbsReal& _keeptagl,
		RooAbsCategory& _flavor,
		RooAbsReal& _wtag,
		RooAbsReal& _delta_wtag,
		double _delta_m,
		bool _mc,
		double _dt_ll,
		double _dt_ul,
		bool _addoutlier,
		double _alpha) :
		RooAbsPdf(name, title),
		dt("dt", "dt", this, _dt),
		tau_b0("tau_b0", "tau_b0", this, _tau_b0),
		expno("expno", "expno", this, _expno),
		costh("costh", "costh", this, _costh),
		ecms("ecms", "ecms", this, _ecms),
		rec_vtntrk("rec_vtntrk", "rec_vtntrk", this, _rec_vtntrk),
		rec_vterr("rec_vterr", "rec_vterr", this, _rec_vterr),
		rec_vtchi2("rec_vtchi2", "rec_vtchi2", this, _rec_vtchi2),
		rec_vtndf("rec_vtndf", "rec_vtndf", this, _rec_vtndf),
		asc_vtntrk("asc_vtntrk", "asc_vtntrk", this, _asc_vtntrk),
		asc_vterr("asc_vterr", "asc_vterr", this, _asc_vterr),
		asc_vtchi2("asc_vtchi2", "asc_vtchi2", this, _asc_vtchi2),
		asc_vtndf("asc_vtndf", "asc_vtndf", this, _asc_vtndf),
		keeptagl("keeptagl", "keeptagl", this, _keeptagl),
		flavor_cat("flavor_cat", "flavor", this, _flavor),
		wtag("wtag", "wtag", this, _wtag),
		delta_wtag("delta_wtag", "delta_wtag", this, _delta_wtag),
		delta_m(_delta_m),
		mc(_mc),
		dt_ll(_dt_ll),
		dt_ul(_dt_ul),
		addoutlier(_addoutlier),
		alpha(_alpha) {
}

RooDtLifetime::RooDtLifetime(const RooDtLifetime& other, const char* name) :
		RooAbsPdf(other, name),
		dt("dt", this, other.dt),
		tau_b0("tau_b0", this, other.tau_b0),
		expno("expno", this, other.expno),
		costh("costh", this, other.costh),
		ecms("ecms", this, other.ecms),
		rec_vtntrk("rec_vtntrk", this, other.rec_vtntrk),
		rec_vterr("rec_vterr", this, other.rec_vterr),
		rec_vtchi2("rec_vtchi2", this, other.rec_vtchi2),
		rec_vtndf("rec_vtndf", this, other.rec_vtndf),
		asc_vtntrk("asc_vtntrk", this, other.asc_vtntrk),
		asc_vterr("asc_vterr", this, other.asc_vterr),
		asc_vtchi2("asc_vtchi2", this, other.asc_vtchi2),
		asc_vtndf("asc_vtndf", this, other.asc_vtndf),
		keeptagl("keeptagl", this, other.keeptagl),
		flavor_cat("flavor_cat", this, other.flavor_cat),
		wtag("wtag", this, other.wtag),
		delta_wtag("delta_wtag", this, other.delta_wtag),
		delta_m(other.delta_m),
		mc(other.mc),
		dt_ll(other.dt_ll),
		dt_ul(other.dt_ul),
		addoutlier(other.addoutlier),
		alpha(other.alpha) {
}

Double_t RooDtLifetime::evaluate() const {
	double a_k, c_k;

	const double amix = flavor_cat * (1 - 2 * wtag);
	const double cexp = 1. - flavor_cat * delta_wtag;
	Belle::CalcAkCk(costh, ecms, &a_k, &c_k, 0);

	Belle::dtres_param_t* dtres_param = Belle::get_dtres_param((int)expno, (int)mc);

	double m_L_e =
			Belle::EfRkRdetRnp_fullrec(dt, 0, tau_b0, a_k, c_k,
					(int)rec_vtntrk, rec_vterr, rec_vtchi2, (int)rec_vtndf,
					(int)asc_vtntrk, asc_vterr, asc_vtchi2, (int)asc_vtndf,
					(int)keeptagl,
					dtres_param);

	double m_int_L_e =
			Belle::norm_EfRkRdetRnp_fullrec(dt_ll, dt_ul, 0, tau_b0, a_k, c_k,
					(int)rec_vtntrk, rec_vterr, rec_vtchi2, (int)rec_vtndf,
					(int)asc_vtntrk, asc_vterr, asc_vtchi2, (int)asc_vtndf,
					(int)keeptagl,
					dtres_param);

        double pdf_sig = cexp*m_L_e; //only for lifetime fit

	if (addoutlier)
		return Belle::AddOutlierWithBkg((int)expno,dt, 1,pdf_sig,pdf_sig,(int)rec_vtntrk, (int)asc_vtntrk,dtres_param, m_int_L_e, m_int_L_e, dt_ll, dt_ul, alpha, 1);
                //return Belle::AddOutlier(expno, dt, m_L_e, rec_vtntrk, asc_vtntrk, dtres_param, m_int_L_e, dt_ll, dt_ul, alpha);
	else
	  return pdf_sig / (2.0*m_int_L_e);
}

Int_t RooDtLifetime::getAnalyticalIntegral(RooArgSet& allVars, RooArgSet& analVars, const char* /*rangeName*/) const {
	if (matchArgs(allVars, analVars, dt)) return 1;
	return 0;
}

Double_t RooDtLifetime::analyticalIntegral(Int_t code, const char* /*rangeName*/) const {
	assert(code == 1);
	return 1;
}
