#
# Makefile for examples
#




MYTARGET_TATAMI = exe/cont_shape
MYOBJS_TATAMI = src_shape/cont_shape.o src_aux/options.o

MYTARGET2_TATAMI = exe/rarebkg_shape
MYOBJS2_TATAMI = src_shape/rarebkg_shape.o src_aux/options.o

MYTARGET3_TATAMI = exe/bb_shape
MYOBJS3_TATAMI = src_shape/bb_shape.o src_aux/options.o

MYTARGET4_TATAMI = exe/scf_shape
MYOBJS4_TATAMI = src_shape/scf_shape.o src_aux/options.o

MYTARGET5_TATAMI = exe/signal_shape
MYOBJS5_TATAMI = src_shape/signal_shape.o src_aux/options.o

MYTARGET6_TATAMI = exe/fullFit
MYOBJS6_TATAMI = src_test/fullFit.o src_aux/options.o

MYTARGET7_TATAMI = exe/toyFit
MYOBJS7_TATAMI = src_test/toyFit.o src_aux/options.o

MYTARGET8_TATAMI = exe/linearityTest
MYOBJS8_TATAMI = src_test/linearityToyFit.o src_aux/options.o

MYTARGET9_TATAMI = exe/linearityTest_v2
MYOBJS9_TATAMI = src_test/linearityToyFit_v2.o src_aux/options.o

MYTARGET10_TATAMI = exe/linearityToyFit_v2_2plus1D
MYOBJS10_TATAMI = src_test/linearityToyFit_v2_2plus1D.o src_aux/options.o

MYTARGET11_TATAMI = exe/cont_shape3D
MYOBJS11_TATAMI = src_shape3D/cont_shape3D.o src_aux/options.o

MYTARGET12_TATAMI = exe/rarebkg_shape3D
MYOBJS12_TATAMI = src_shape3D/rarebkg_shape3D.o src_aux/options.o

MYTARGET13_TATAMI = exe/bb_shape3D
MYOBJS13_TATAMI = src_shape3D/bb_shape3D.o src_aux/options.o

MYTARGET14_TATAMI = exe/scf_shape3D
MYOBJS14_TATAMI = src_shape3D/scf_shape3D.o src_aux/options.o

MYTARGET15_TATAMI = exe/signal_shape3D
MYOBJS15_TATAMI = src_shape3D/signal_shape3D.o src_aux/options.o

MYTARGET16_TATAMI = exe/linearityTest_v2_3DShapeFix
MYOBJS16_TATAMI = src_test/linearityToyFit_v2_3DShapeFix.o src_aux/options.o

MYTARGET17_TATAMI = exe/signal_shape3D_KDE
MYOBJS17_TATAMI = src_shape3D/signal_shape3D_KDE.o src_aux/options.o

MYTARGET18_TATAMI = exe/linearityToyFit_v2_3DKDE
MYOBJS18_TATAMI = src_test/linearityToyFit_v2_3DKDE.o src_aux/options.o

MYTARGET19_TATAMI = exe/linearity_sigOnly_reco
MYOBJS19_TATAMI = src_test/linearity_sigOnly_reco.o src_aux/options.o

MYTARGET20_TATAMI = exe/linearity_sigOnly_reco1D
MYOBJS20_TATAMI = src_test/linearity_sigOnly_reco1D.o src_aux/options.o

MYTARGET21_TATAMI = exe/linearity_sigOnly_gen
MYOBJS21_TATAMI = src_test/linearity_sigOnly_gen.o src_aux/options.o

MYTARGET22_TATAMI = exe/linearity_sigOnly_reco1D_genFlav
MYOBJS22_TATAMI = src_test/linearity_sigOnly_reco1D_genFlav.o src_aux/options.o

MYTARGET23_TATAMI = exe/linearity_sigOnly_reco1D_correctedMistag
MYOBJS23_TATAMI = src_test/linearity_sigOnly_reco1D_correctedMistag.o src_aux/options.o

MYTARGET24_TATAMI = exe/linearityToyFit_v2_binBybin
MYOBJS24_TATAMI = src_test/linearityToyFit_v2_binBybin.o src_aux/options.o

MYTARGET25_TATAMI = exe/linearityToyFit_v2_correctMCMistag
MYOBJS25_TATAMI = src_test/linearityToyFit_v2_correctMCMistag.o src_aux/options.o

MYTARGET26_TATAMI = exe/linearityToyFit_v2_correctMCMistag_byBin
MYOBJS26_TATAMI = src_test/linearityToyFit_v2_correctMCMistag_byBin.o src_aux/options.o

MYTARGET27_TATAMI = exe/linearityToyFit_v2_3DKDE_correctMCMistag
MYOBJS27_TATAMI = src_test/linearityToyFit_v2_3DKDE_correctMCMistag.o src_aux/options.o

MYTARGET28_TATAMI = exe/mbckDE_2DFit_yieldBiasCheck
MYOBJS28_TATAMI = src_test/mbckDE_2DFit_yieldBiasCheck.o src_aux/options.o

MYTARGET29_TATAMI = exe/sigOnly_genDt_simFit
MYOBJS29_TATAMI = src_test/sigOnly_genDt_simFit.o src_aux/options.o

MYTARGET30_TATAMI = exe/lifetime_fit
MYOBJS30_TATAMI = src_test/lifetime_fit.o src_aux/options.o

MYTARGET31_TATAMI = exe/dalitzFit
MYOBJS31_TATAMI = src_test/dalitzFit.o src_aux/options.o

MYTARGET32_TATAMI = exe/fullFit_explicitPDFdefinitions
MYOBJS32_TATAMI = src_main/fullFit_explicitPDFdefinitions.o src_aux/options.o

MYTARGET33_TATAMI = exe/dalitzFit_explicitPDFdefinitions
MYOBJS33_TATAMI = src_main/dalitzFit_explicitPDFdefinitions.o src_aux/options.o

MYTARGET34_TATAMI = exe/fixedShape_syst
MYOBJS34_TATAMI = src_systematics/fixedShape_syst.o src_aux/options.o

MYTARGET35_TATAMI = exe/bb_random_shape
MYOBJS35_TATAMI = src_shape_new/bb_random_shape.o src_aux/options.o

MYTARGET36_TATAMI = exe/cont_random_shape
MYOBJS36_TATAMI = src_shape_new/cont_random_shape.o src_aux/options.o

MYTARGET37_TATAMI = exe/signal_pure_shape
MYOBJS37_TATAMI = src_shape_new/signal_pure_shape.o src_aux/options.o

MYTARGET38_TATAMI = exe/bb_realBmother_shape
MYOBJS38_TATAMI = src_shape_new/bb_realBmother_shape.o src_aux/options.o

MYTARGET39_TATAMI = exe/scf_random_shape
MYOBJS39_TATAMI = src_shape_new/scf_random_shape.o src_aux/options.o

MYTARGET40_TATAMI = exe/randomize_wtagFractions
MYOBJS40_TATAMI = src_systematics/randomize_wtagFractions.o src_aux/options.o

MYTARGET41_TATAMI = exe/wtag_syst
MYOBJS41_TATAMI = src_systematics/wtag_syst.o src_aux/options.o

MYTARGET42_TATAMI = exe/signalOnly_LifetimeFit
MYOBJS42_TATAMI = src_main/signalOnly_LifetimeFit.o src_aux/options.o

MYTARGET43_TATAMI = exe/randomize_deltaMtauB
MYOBJS43_TATAMI = src_systematics/randomize_deltaMtauB.o src_aux/options.o

MYTARGET44_TATAMI = exe/deltaMtauB_syst
MYOBJS44_TATAMI = src_systematics/deltaMtauB_syst.o src_aux/options.o

MYTARGET45_TATAMI = exe/fixedShape_syst_dalitz
MYOBJS45_TATAMI = src_systematics/fixedShape_syst_dalitz.o src_aux/options.o

MYTARGET46_TATAMI = exe/wtag_syst_dalitz
MYOBJS46_TATAMI = src_systematics/wtag_syst_dalitz.o src_aux/options.o

MYTARGET47_TATAMI = exe/deltaMtauB_syst_dalitz
MYOBJS47_TATAMI = src_systematics/deltaMtauB_syst_dalitz.o src_aux/options.o

MYTARGET48_TATAMI = exe/belle2_qq_deltaT_trialFit
MYOBJS48_TATAMI = src_test/belle2_qq_deltaT_trialFit.o src_aux/options.o

# Compiler
CXX = g++

# Optimization and Debug flags
OPT = -O2 #-g -v

# Other compiler flags
CXXFLAGS = $(OPT) -Wall -Wextra -std=c++0x

# ROOT flags and libs
ROOT_FLAGS_INC = $(shell root-config --cflags)
ROOT_LIB = $(shell root-config --libs)
ROOFIT_LIB = -lRooFitCore -lRooFit -lHtml -lMinuit -lFoam -lGui
# Link against libMathMore if it exists
ROOFIT_LIB += $(shell if [ -e $(ROOTSYS)/lib/libMathMore.so ]; then echo -lMathMore; fi)

# Boost Library
BOOST_LIB = -lboost_program_options -lboost_serialization

# libRooComplexPDF
LCPDF_INC = -I$(BELLE_FLC)
LCPDF_LIB = -L$(BELLE_FLC)/libComplexPDF -lComplexPDF

# libRooComplexPDF
LRCPDF_INC = -I$(BELLE_FLC) $(LCPDF_INC)
LRCPDF_LIB = -L$(BELLE_FLC)/libRooComplexPDF -lRooComplexPDF $(LCPDF_LIB)

# libRooTatami
LRT_INC = -I$(BELLE_FLC)
LRT_LIB = -L$(BELLE_FLC)/libRooTatami

# All Includes
INCS = -I. $(ROOT_FLAGS_INC) $(LRCPDF_INC) $(LRT_INC)

# All libs 
LIBS = -L. $(ROOT_LIB) $(ROOFIT_LIB) $(BOOST_LIB)

.SUFFIXES: .c .cc

# C++ source files
.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCS) -o $@ $<

# ------------------------------------------------------------------------

all::
ifdef BELLE_LEVEL
	@echo "BELLE_LEVEL "$(BELLE_LEVEL)" detected"
	$(MAKE) $(MYTARGET_TATAMI)
	$(MAKE) $(MYTARGET2_TATAMI)
	$(MAKE) $(MYTARGET3_TATAMI)
	$(MAKE) $(MYTARGET4_TATAMI)
	$(MAKE) $(MYTARGET5_TATAMI)
	$(MAKE) $(MYTARGET6_TATAMI)
	$(MAKE) $(MYTARGET7_TATAMI)
	$(MAKE) $(MYTARGET8_TATAMI)
	$(MAKE) $(MYTARGET9_TATAMI)
	$(MAKE) $(MYTARGET10_TATAMI)
	$(MAKE) $(MYTARGET11_TATAMI)
	$(MAKE) $(MYTARGET12_TATAMI)
	$(MAKE) $(MYTARGET13_TATAMI)
	$(MAKE) $(MYTARGET14_TATAMI)
	$(MAKE) $(MYTARGET15_TATAMI)
	$(MAKE) $(MYTARGET16_TATAMI)
	$(MAKE) $(MYTARGET17_TATAMI)
	$(MAKE) $(MYTARGET18_TATAMI)
	$(MAKE) $(MYTARGET19_TATAMI)
	$(MAKE) $(MYTARGET20_TATAMI)
	$(MAKE) $(MYTARGET21_TATAMI)
	$(MAKE) $(MYTARGET22_TATAMI)
	$(MAKE) $(MYTARGET23_TATAMI)
	$(MAKE) $(MYTARGET24_TATAMI)
	$(MAKE) $(MYTARGET25_TATAMI)
	$(MAKE) $(MYTARGET26_TATAMI)
	$(MAKE) $(MYTARGET27_TATAMI)
	$(MAKE) $(MYTARGET28_TATAMI)
	$(MAKE) $(MYTARGET29_TATAMI)
	$(MAKE) $(MYTARGET30_TATAMI)
	$(MAKE) $(MYTARGET31_TATAMI)
	$(MAKE) $(MYTARGET32_TATAMI)
	$(MAKE) $(MYTARGET33_TATAMI)
	$(MAKE) $(MYTARGET34_TATAMI)
	$(MAKE) $(MYTARGET35_TATAMI)
	$(MAKE) $(MYTARGET36_TATAMI)
	$(MAKE) $(MYTARGET37_TATAMI)	
	$(MAKE) $(MYTARGET38_TATAMI)
	$(MAKE) $(MYTARGET39_TATAMI)
	$(MAKE) $(MYTARGET40_TATAMI)
	$(MAKE) $(MYTARGET41_TATAMI)
	$(MAKE) $(MYTARGET42_TATAMI)
	$(MAKE) $(MYTARGET43_TATAMI)
	$(MAKE) $(MYTARGET44_TATAMI)
	$(MAKE) $(MYTARGET45_TATAMI)
	$(MAKE) $(MYTARGET46_TATAMI)
	$(MAKE) $(MYTARGET47_TATAMI)
	$(MAKE) $(MYTARGET48_TATAMI)

else
	@echo "-----------------------------------------------------------------------"
	@echo "Belle software seems not to be installed on this machine. At least the"
	@echo "BELLE_LEVEL environment variable does not exist. Probably you need to"
	@echo "source the bashrc_general or cshrc_general."
	@echo "-----------------------------------------------------------------------"
	@echo -n "Searching for precompiled libRooTatamiPortable.so ... "
ifeq ($(shell if [ -e $(BELLE_FLC)/libRooTatami/libRooTatamiPortable.so ]; then echo -lRooTatamiPortable; fi), -lRooTatamiPortable)
	@echo "OK"
	@echo "Using precompiled libRooTatamiPortable.so to built $(TARGET_TATAMI)"
	@echo "-----------------------------------------------------------------------"
	$(MAKE) $(MYTARGET_TATAMI)
	$(MAKE) $(MYTARGET2_TATAMI)
	$(MAKE) $(MYTARGET3_TATAMI)
	$(MAKE) $(MYTARGET4_TATAMI)
	$(MAKE) $(MYTARGET5_TATAMI)
	$(MAKE) $(MYTARGET6_TATAMI)
	$(MAKE) $(MYTARGET7_TATAMI)
	$(MAKE) $(MYTARGET8_TATAMI)
	$(MAKE) $(MYTARGET9_TATAMI)
	$(MAKE) $(MYTARGET10_TATAMI)
	$(MAKE) $(MYTARGET11_TATAMI)
	$(MAKE) $(MYTARGET12_TATAMI)
	$(MAKE) $(MYTARGET13_TATAMI)
	$(MAKE) $(MYTARGET14_TATAMI)
	$(MAKE) $(MYTARGET15_TATAMI)
	$(MAKE) $(MYTARGET16_TATAMI)
	$(MAKE) $(MYTARGET17_TATAMI)
	$(MAKE) $(MYTARGET18_TATAMI)
	$(MAKE) $(MYTARGET19_TATAMI)
	$(MAKE) $(MYTARGET20_TATAMI)
	$(MAKE) $(MYTARGET21_TATAMI)
	$(MAKE) $(MYTARGET22_TATAMI)
	$(MAKE) $(MYTARGET23_TATAMI)
	$(MAKE) $(MYTARGET24_TATAMI)
	$(MAKE) $(MYTARGET25_TATAMI)
	$(MAKE) $(MYTARGET26_TATAMI)
	$(MAKE) $(MYTARGET27_TATAMI)
	$(MAKE) $(MYTARGET28_TATAMI)
	$(MAKE) $(MYTARGET29_TATAMI)
	$(MAKE) $(MYTARGET30_TATAMI)
	$(MAKE) $(MYTARGET31_TATAMI)
	$(MAKE) $(MYTARGET32_TATAMI)
	$(MAKE) $(MYTARGET33_TATAMI)
	$(MAKE) $(MYTARGET34_TATAMI)
	$(MAKE) $(MYTARGET35_TATAMI)
	$(MAKE) $(MYTARGET36_TATAMI)
	$(MAKE) $(MYTARGET37_TATAMI)
	$(MAKE) $(MYTARGET38_TATAMI)
	$(MAKE) $(MYTARGET39_TATAMI)
	$(MAKE) $(MYTARGET40_TATAMI)
	$(MAKE) $(MYTARGET41_TATAMI)
	$(MAKE) $(MYTARGET42_TATAMI)
	$(MAKE) $(MYTARGET43_TATAMI)
	$(MAKE) $(MYTARGET44_TATAMI)
	$(MAKE) $(MYTARGET45_TATAMI)
	$(MAKE) $(MYTARGET46_TATAMI)
	$(MAKE) $(MYTARGET47_TATAMI)
	$(MAKE) $(MYTARGET48_TATAMI)

else
	@echo "FAILED"
	@echo "Skipping built of $(MYTARGET_TATAMI)"
	@echo "Skipping built of $(MYTARGET2_TATAMI)"
	@echo "Skipping built of $(MYTARGET3_TATAMI)"
	@echo "Skipping built of $(MYTARGET4_TATAMI)"
	@echo "Skipping built of $(MYTARGET5_TATAMI)"
	@echo "Skipping built of $(MYTARGET6_TATAMI)"
	@echo "Skipping built of $(MYTARGET7_TATAMI)"
	@echo "Skipping built of $(MYTARGET8_TATAMI)"
	@echo "Skipping built of $(MYTARGET9_TATAMI)"
	@echo "Skipping built of $(MYTARGET10_TATAMI)"
	@echo "Skipping built of $(MYTARGET11_TATAMI)"
	@echo "Skipping built of $(MYTARGET12_TATAMI)"
	@echo "Skipping built of $(MYTARGET13_TATAMI)"
	@echo "Skipping built of $(MYTARGET14_TATAMI)"
	@echo "Skipping built of $(MYTARGET15_TATAMI)"
	@echo "Skipping built of $(MYTARGET16_TATAMI)"
	@echo "Skipping built of $(MYTARGET17_TATAMI)"
	@echo "Skipping built of $(MYTARGET18_TATAMI)"
	@echo "Skipping built of $(MYTARGET19_TATAMI)"
	@echo "Skipping built of $(MYTARGET20_TATAMI)"
	@echo "Skipping built of $(MYTARGET21_TATAMI)"
	@echo "Skipping built of $(MYTARGET22_TATAMI)"
	@echo "Skipping built of $(MYTARGET23_TATAMI)"
	@echo "Skipping built of $(MYTARGET24_TATAMI)"
	@echo "Skipping built of $(MYTARGET25_TATAMI)"
	@echo "Skipping built of $(MYTARGET26_TATAMI)"
	@echo "Skipping built of $(MYTARGET27_TATAMI)"
	@echo "Skipping built of $(MYTARGET28_TATAMI)"
	@echo "Skipping built of $(MYTARGET29_TATAMI)"
	@echo "Skipping built of $(MYTARGET30_TATAMI)"
	@echo "Skipping built of $(MYTARGET31_TATAMI)"
	@echo "Skipping built of $(MYTARGET32_TATAMI)"
	@echo "Skipping built of $(MYTARGET33_TATAMI)"
	@echo "Skipping built of $(MYTARGET34_TATAMI)"
	@echo "Skipping built of $(MYTARGET35_TATAMI)"
	@echo "Skipping built of $(MYTARGET36_TATAMI)"
	@echo "Skipping built of $(MYTARGET37_TATAMI)"
	@echo "Skipping built of $(MYTARGET38_TATAMI)"
	@echo "Skipping built of $(MYTARGET39_TATAMI)"
	@echo "Skipping built of $(MYTARGET40_TATAMI)"
	@echo "Skipping built of $(MYTARGET41_TATAMI)"
	@echo "Skipping built of $(MYTARGET42_TATAMI)"
	@echo "Skipping built of $(MYTARGET43_TATAMI)"
	@echo "Skipping built of $(MYTARGET44_TATAMI)"
	@echo "Skipping built of $(MYTARGET45_TATAMI)"
	@echo "Skipping built of $(MYTARGET46_TATAMI)"
	@echo "Skipping built of $(MYTARGET47_TATAMI)"
	@echo "Skipping built of $(MYTARGET48_TATAMI)"
	@echo "-----------------------------------------------------------------------"
endif
endif



ifndef BELLE_LEVEL
$(MYTARGET_TATAMI): $(MYOBJS_TATAMI)
	$(CXX) -o $@ $(MYOBJS_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable 

$(MYTARGET2_TATAMI): $(MYOBJS2_TATAMI)
	$(CXX) -o $@ $(MYOBJS2_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable 

$(MYTARGET3_TATAMI): $(MYOBJS3_TATAMI)
	$(CXX) -o $@ $(MYOBJS3_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET4_TATAMI): $(MYOBJS4_TATAMI)
	$(CXX) -o $@ $(MYOBJS4_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET5_TATAMI): $(MYOBJS5_TATAMI)
	$(CXX) -o $@ $(MYOBJS5_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET6_TATAMI): $(MYOBJS6_TATAMI)
	$(CXX) -o $@ $(MYOBJS6_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET7_TATAMI): $(MYOBJS7_TATAMI)
	$(CXX) -o $@ $(MYOBJS7_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET8_TATAMI): $(MYOBJS8_TATAMI)
	$(CXX) -o $@ $(MYOBJS8_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET9_TATAMI): $(MYOBJS9_TATAMI)
	$(CXX) -o $@ $(MYOBJS9_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET10_TATAMI): $(MYOBJS10_TATAMI)
	$(CXX) -o $@ $(MYOBJS10_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET11_TATAMI): $(MYOBJS11_TATAMI)
	$(CXX) -o $@ $(MYOBJS11_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable 

$(MYTARGET12_TATAMI): $(MYOBJS12_TATAMI)
	$(CXX) -o $@ $(MYOBJS12_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable 

$(MYTARGET13_TATAMI): $(MYOBJS13_TATAMI)
	$(CXX) -o $@ $(MYOBJS13_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET14_TATAMI): $(MYOBJS14_TATAMI)
	$(CXX) -o $@ $(MYOBJS14_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET15_TATAMI): $(MYOBJS15_TATAMI)
	$(CXX) -o $@ $(MYOBJS15_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET16_TATAMI): $(MYOBJS16_TATAMI)
	$(CXX) -o $@ $(MYOBJS16_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET17_TATAMI): $(MYOBJS17_TATAMI)
	$(CXX) -o $@ $(MYOBJS17_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET18_TATAMI): $(MYOBJS18_TATAMI)
	$(CXX) -o $@ $(MYOBJS18_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET19_TATAMI): $(MYOBJS19_TATAMI)
	$(CXX) -o $@ $(MYOBJS19_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET20_TATAMI): $(MYOBJS20_TATAMI)
	$(CXX) -o $@ $(MYOBJS20_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET21_TATAMI): $(MYOBJS21_TATAMI)
	$(CXX) -o $@ $(MYOBJS21_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET22_TATAMI): $(MYOBJS22_TATAMI)
	$(CXX) -o $@ $(MYOBJS22_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET23_TATAMI): $(MYOBJS23_TATAMI)
	$(CXX) -o $@ $(MYOBJS23_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET24_TATAMI): $(MYOBJS24_TATAMI)
	$(CXX) -o $@ $(MYOBJS24_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET25_TATAMI): $(MYOBJS25_TATAMI)
	$(CXX) -o $@ $(MYOBJS25_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET26_TATAMI): $(MYOBJS26_TATAMI)
	$(CXX) -o $@ $(MYOBJS26_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET27_TATAMI): $(MYOBJS27_TATAMI)
	$(CXX) -o $@ $(MYOBJS27_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET28_TATAMI): $(MYOBJS28_TATAMI)
	$(CXX) -o $@ $(MYOBJS28_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET29_TATAMI): $(MYOBJS29_TATAMI)
	$(CXX) -o $@ $(MYOBJS29_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET30_TATAMI): $(MYOBJS30_TATAMI)
	$(CXX) -o $@ $(MYOBJS30_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET31_TATAMI): $(MYOBJS31_TATAMI)
	$(CXX) -o $@ $(MYOBJS31_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET32_TATAMI): $(MYOBJS32_TATAMI)
	$(CXX) -o $@ $(MYOBJS32_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET33_TATAMI): $(MYOBJS33_TATAMI)
	$(CXX) -o $@ $(MYOBJS33_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET34_TATAMI): $(MYOBJS34_TATAMI)
	$(CXX) -o $@ $(MYOBJS34_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET35_TATAMI): $(MYOBJS35_TATAMI)
	$(CXX) -o $@ $(MYOBJS35_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET36_TATAMI): $(MYOBJS36_TATAMI)
	$(CXX) -o $@ $(MYOBJS36_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET37_TATAMI): $(MYOBJS37_TATAMI)
	$(CXX) -o $@ $(MYOBJS37_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET38_TATAMI): $(MYOBJS38_TATAMI)
	$(CXX) -o $@ $(MYOBJS38_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET39_TATAMI): $(MYOBJS39_TATAMI)
	$(CXX) -o $@ $(MYOBJS39_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET40_TATAMI): $(MYOBJS40_TATAMI)
	$(CXX) -o $@ $(MYOBJS40_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET41_TATAMI): $(MYOBJS41_TATAMI)
	$(CXX) -o $@ $(MYOBJS41_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET42_TATAMI): $(MYOBJS42_TATAMI)
	$(CXX) -o $@ $(MYOBJS42_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET43_TATAMI): $(MYOBJS43_TATAMI)
	$(CXX) -o $@ $(MYOBJS43_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET44_TATAMI): $(MYOBJS44_TATAMI)
	$(CXX) -o $@ $(MYOBJS44_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET45_TATAMI): $(MYOBJS45_TATAMI)
	$(CXX) -o $@ $(MYOBJS45_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET46_TATAMI): $(MYOBJS46_TATAMI)
	$(CXX) -o $@ $(MYOBJS46_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET47_TATAMI): $(MYOBJS47_TATAMI)
	$(CXX) -o $@ $(MYOBJS47_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

$(MYTARGET48_TATAMI): $(MYOBJS48_TATAMI)
	$(CXX) -o $@ $(MYOBJS48_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatamiPortable

else
$(MYTARGET_TATAMI): $(MYOBJS_TATAMI)
	$(CXX) -o $@ $(MYOBJS_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET2_TATAMI): $(MYOBJS2_TATAMI)
	$(CXX) -o $@ $(MYOBJS2_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET3_TATAMI): $(MYOBJS3_TATAMI)
	$(CXX) -o $@ $(MYOBJS3_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET4_TATAMI): $(MYOBJS4_TATAMI)
	$(CXX) -o $@ $(MYOBJS4_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET5_TATAMI): $(MYOBJS5_TATAMI)
	$(CXX) -o $@ $(MYOBJS5_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET6_TATAMI): $(MYOBJS6_TATAMI)
	$(CXX) -o $@ $(MYOBJS6_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET7_TATAMI): $(MYOBJS7_TATAMI)
	$(CXX) -o $@ $(MYOBJS7_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET8_TATAMI): $(MYOBJS8_TATAMI)
	$(CXX) -o $@ $(MYOBJS8_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET9_TATAMI): $(MYOBJS9_TATAMI)
	$(CXX) -o $@ $(MYOBJS9_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET10_TATAMI): $(MYOBJS10_TATAMI)
	$(CXX) -o $@ $(MYOBJS10_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET11_TATAMI): $(MYOBJS11_TATAMI)
	$(CXX) -o $@ $(MYOBJS11_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET12_TATAMI): $(MYOBJS12_TATAMI)
	$(CXX) -o $@ $(MYOBJS12_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET13_TATAMI): $(MYOBJS13_TATAMI)
	$(CXX) -o $@ $(MYOBJS13_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET14_TATAMI): $(MYOBJS14_TATAMI)
	$(CXX) -o $@ $(MYOBJS14_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET15_TATAMI): $(MYOBJS15_TATAMI)
	$(CXX) -o $@ $(MYOBJS15_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET16_TATAMI): $(MYOBJS16_TATAMI)
	$(CXX) -o $@ $(MYOBJS16_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET17_TATAMI): $(MYOBJS17_TATAMI)
	$(CXX) -o $@ $(MYOBJS17_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET18_TATAMI): $(MYOBJS18_TATAMI)
	$(CXX) -o $@ $(MYOBJS18_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET19_TATAMI): $(MYOBJS19_TATAMI)
	$(CXX) -o $@ $(MYOBJS19_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET20_TATAMI): $(MYOBJS20_TATAMI)
	$(CXX) -o $@ $(MYOBJS20_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET21_TATAMI): $(MYOBJS21_TATAMI)
	$(CXX) -o $@ $(MYOBJS21_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET22_TATAMI): $(MYOBJS22_TATAMI)
	$(CXX) -o $@ $(MYOBJS22_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET23_TATAMI): $(MYOBJS23_TATAMI)
	$(CXX) -o $@ $(MYOBJS23_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET24_TATAMI): $(MYOBJS24_TATAMI)
	$(CXX) -o $@ $(MYOBJS24_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET25_TATAMI): $(MYOBJS25_TATAMI)
	$(CXX) -o $@ $(MYOBJS25_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET26_TATAMI): $(MYOBJS26_TATAMI)
	$(CXX) -o $@ $(MYOBJS26_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET27_TATAMI): $(MYOBJS27_TATAMI)
	$(CXX) -o $@ $(MYOBJS27_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET28_TATAMI): $(MYOBJS28_TATAMI)
	$(CXX) -o $@ $(MYOBJS28_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET29_TATAMI): $(MYOBJS29_TATAMI)
	$(CXX) -o $@ $(MYOBJS29_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET30_TATAMI): $(MYOBJS30_TATAMI)
	$(CXX) -o $@ $(MYOBJS30_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET31_TATAMI): $(MYOBJS31_TATAMI)
	$(CXX) -o $@ $(MYOBJS31_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET32_TATAMI): $(MYOBJS32_TATAMI)
	$(CXX) -o $@ $(MYOBJS32_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET33_TATAMI): $(MYOBJS33_TATAMI)
	$(CXX) -o $@ $(MYOBJS33_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET34_TATAMI): $(MYOBJS34_TATAMI)
	$(CXX) -o $@ $(MYOBJS34_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET35_TATAMI): $(MYOBJS35_TATAMI)
	$(CXX) -o $@ $(MYOBJS35_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET36_TATAMI): $(MYOBJS36_TATAMI)
	$(CXX) -o $@ $(MYOBJS36_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET37_TATAMI): $(MYOBJS37_TATAMI)
	$(CXX) -o $@ $(MYOBJS37_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET38_TATAMI): $(MYOBJS38_TATAMI)
	$(CXX) -o $@ $(MYOBJS38_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET39_TATAMI): $(MYOBJS39_TATAMI)
	$(CXX) -o $@ $(MYOBJS39_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET40_TATAMI): $(MYOBJS40_TATAMI)
	$(CXX) -o $@ $(MYOBJS40_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET41_TATAMI): $(MYOBJS41_TATAMI)
	$(CXX) -o $@ $(MYOBJS41_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET42_TATAMI): $(MYOBJS42_TATAMI)
	$(CXX) -o $@ $(MYOBJS42_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET43_TATAMI): $(MYOBJS43_TATAMI)
	$(CXX) -o $@ $(MYOBJS43_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET44_TATAMI): $(MYOBJS44_TATAMI)
	$(CXX) -o $@ $(MYOBJS44_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET45_TATAMI): $(MYOBJS45_TATAMI)
	$(CXX) -o $@ $(MYOBJS45_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET46_TATAMI): $(MYOBJS46_TATAMI)
	$(CXX) -o $@ $(MYOBJS46_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET47_TATAMI): $(MYOBJS47_TATAMI)
	$(CXX) -o $@ $(MYOBJS47_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

$(MYTARGET48_TATAMI): $(MYOBJS48_TATAMI)
	$(CXX) -o $@ $(MYOBJS48_TATAMI) $(LIBS) $(LRT_LIB) -lRooTatami

endif


clean::
	rm -f $(MYOBJS_TATAMI)
	rm -f $(MYOBJS2_TATAMI)
	rm -f $(MYOBJS3_TATAMI)
	rm -f $(MYOBJS4_TATAMI)
	rm -f $(MYOBJS5_TATAMI)
	rm -f $(MYOBJS6_TATAMI)
	rm -f $(MYOBJS7_TATAMI)
	rm -f $(MYOBJS8_TATAMI)
	rm -f $(MYOBJS9_TATAMI)
	rm -f $(MYOBJS10_TATAMI)
	rm -f $(MYOBJS11_TATAMI)
	rm -f $(MYOBJS12_TATAMI)
	rm -f $(MYOBJS13_TATAMI)
	rm -f $(MYOBJS14_TATAMI)
	rm -f $(MYOBJS15_TATAMI)
	rm -f $(MYOBJS16_TATAMI)
	rm -f $(MYOBJS17_TATAMI)
	rm -f $(MYOBJS18_TATAMI)
	rm -f $(MYOBJS19_TATAMI)
	rm -f $(MYOBJS20_TATAMI)
	rm -f $(MYOBJS21_TATAMI)
	rm -f $(MYOBJS22_TATAMI)
	rm -f $(MYOBJS23_TATAMI)
	rm -f $(MYOBJS24_TATAMI)
	rm -f $(MYOBJS25_TATAMI)
	rm -f $(MYOBJS26_TATAMI)
	rm -f $(MYOBJS27_TATAMI)
	rm -f $(MYOBJS28_TATAMI)
	rm -f $(MYOBJS29_TATAMI)
	rm -f $(MYOBJS30_TATAMI)
	rm -f $(MYOBJS31_TATAMI)
	rm -f $(MYOBJS32_TATAMI)
	rm -f $(MYOBJS33_TATAMI)
	rm -f $(MYOBJS34_TATAMI)
	rm -f $(MYOBJS35_TATAMI)
	rm -f $(MYOBJS36_TATAMI)
	rm -f $(MYOBJS37_TATAMI)
	rm -f $(MYOBJS38_TATAMI)
	rm -f $(MYOBJS39_TATAMI)
	rm -f $(MYOBJS40_TATAMI)
	rm -f $(MYOBJS41_TATAMI)
	rm -f $(MYOBJS42_TATAMI)
	rm -f $(MYOBJS43_TATAMI)
	rm -f $(MYOBJS44_TATAMI)
	rm -f $(MYOBJS45_TATAMI)
	rm -f $(MYOBJS46_TATAMI)
	rm -f $(MYOBJS47_TATAMI)
	rm -f $(MYOBJS48_TATAMI)








